#!/usr/bin/env bash

# NetDiff (c) Paul C. Buetow (2014)
# http://netdiff.buetow.org

declare -r VERSION='VERSION_DEVEL'
declare -i RC=0

declare -r SERVER="${1}"    ; shift
declare -r WHAT="${1}"      ; shift
declare -i PORT="${1}"      ; shift
declare    DIFF_OPTS="${1}" ; shift


usage () {
  cat <<USAGE
This is NetDiff ${VERSION}. Usage:
  netdiff SERVER WHAT [PORT=1234] [DIFF OPTS]
USAGE
}

[ -f /etc/default/netdiff ] && source /etc/default/netdiff

[ -z "${WHAT}" ] && usage && exit 0
[ -z "${DIFF_OPTS}" ] && DIFF_OPTS="${DEFAULT_DIFF_OPTS}"

[[ -z "${PORT}" || ${PORT} == 0 ]] && PORT=${DEFAULT_PORT}

declare -r TMPWHAT=$(mktemp --directory)
declare -r BASENAME=$(basename "${WHAT}")

cd $(dirname "${WHAT}")

# An attacker does not know which file is diffed. So it's a shared secret
# between the two hosts
declare -r AESPASS=$(md5sum <<< "${SERVER}:${PORT}/${WHAT}" | cut -d' ' -f1)
declare -r OPENSSL_OPTS="enc -aes-256-cbc -base64 -salt -pass pass:${AESPASS}"

set -o pipefail

if [[ "${SERVER}" == "$(hostname)" || 
  "${SERVER}" == "$(hostname --fqdn)" ]]; then
  tar -cf - "${BASENAME}" |
  openssl ${OPENSSL_OPTS} |
  nc -l -p ${PORT} |
  openssl ${OPENSSL_OPTS} -d |
  tar -xf - --directory ${TMPWHAT}
  RC=$?
else
  sleep 0.1
  tar -cf - "${BASENAME}" |
  openssl ${OPENSSL_OPTS} |
  nc ${SERVER} ${PORT} |
  openssl ${OPENSSL_OPTS} -d |
  tar -xf - --directory ${TMPWHAT}
  RC=$?
fi

if [ ${RC} -ne 0 ]; then
  echo 'Something went wrong, could not diff'
  # Default trouble exit status of diff 
  RC=2 
else
  diff $@ "${WHAT}" "${TMPWHAT}/${BASENAME}" ${DIFF_OPTS}
  RC=$?
fi

[ -d ${TMPWHAT} ] && rm -rf ${TMPWHAT}
exit ${RC}

